### ISSUE TITLE
Setting the spinner color programmatically does not work

### ISSUE THREAD

**Issue by aldwinbabierra** [skydoves/ExpandableLayout#12]
I tried to use **setSpinnerColor(int)** after expanding, but does not update already showing expanded layout. Changing the spinner color in xml works, but not programmatically.

**Comment by skydoves** [comment]
Hi, @aldwinbabierra!
It is released a new version [1.0.6](https://github.com/skydoves/ExpandableLayout/releases)!
Please check to work well using the new release.
Thank you for your issue :)
