### ISSUE TITLE
Error inflating class on Android 4.x

### ISSUE THREAD

**Issue by thereisonlywe** [skydoves/ExpandableLayout#13]
- Library Version [v1.0.5]
- Affected Device(s) [AS emulator 4.2, 4.4]
 
**Describe the Bug:**
When inflating the layout containing expandablelayout, the app crashes. Unfortunately not much is reported to the logcat. Only "Error inflating class com.skydoves.expandablelayout"

**Expected Behavior:**
It should work as it does on Android 7 and 10; I tested on.

**This is where it crashes**
LayoutInflater.from(MainActivity.this).inflate(R.layout.activity_main_settings, null, false);

**Below is how I use this library inside my layout**
<com.skydoves.expandablelayout.ExpandableLayout
        android:id="@+id/ABC"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="6dp"
        app:expandable_duration="150"
        app:expandable_isExpanded="false"
        app:expandable_parentLayout="@layout/abc_parent"
        app:expandable_secondLayout="@layout/abc_child"
        app:expandable_showSpinner="true"
        app:expandable_spinner="@drawable/ic_arrow_down"
        app:expandable_spinner_color="@color/violetDark"
        app:expandable_spinner_animate="true"
        app:expandable_spinner_margin="0dp"
        app:expandable_spinner_size="36dp"/>

**Comment by skydoves** [comment]
Hi, @thereisonlywe!
It is released a new version [1.0.6](https://github.com/skydoves/ExpandableLayout/releases)!
Please check to work well using the new release.
Thank you for your issue :)

**Comment by skydoves** [comment]
Fix confirmed.

**Comment by hoseinimohamad** [comment]
> Fix confirmed.
The problem remains!
