### ISSUE TITLE
Spinner margin doesn't work when the layout is RTL

### ISSUE THREAD

**Issue by thereisonlywe** [skydoves/ExpandableLayout#14]
- Library Version [v1.0.5]
- Affected Device(s) [AS emulator Android 10]
 
**Describe the Bug:**
Setting "app:expandable_spinner_margin" has no effect when the layout is RTL.

**Comment by skydoves** [comment]
Hi, @thereisonlywe!
It is released a new version [1.0.6](https://github.com/skydoves/ExpandableLayout/releases)!
Please check to work well using the new release.
Thank you for your issue :)

**Comment by skydoves** [comment]
Fix confirmed.
