### ISSUE TITLE
demo project

### ISSUE THREAD

**Issue by Cianid** [skydoves/ExpandableLayout#16]
Hi. The lib looks awesome.Hovewer I was not able set up layouts properly(. Can you please add some demo project?

**Comment by skydoves** [comment]
Hi,
This is the [demo](https://github.com/skydoves/ExpandableLayout/tree/master/app) project.
Thanks.

**Comment by Cianid** [comment]
> Hi,
> This is the [demo](https://github.com/skydoves/ExpandableLayout/tree/master/app) project.
> Thanks.

Hi again. Thanks!
