### ISSUE TITLE
How can I show ListView or RecyclerView inside secondLayout?

### ISSUE THREAD

**Issue by Pirokar** [skydoves/ExpandableLayout#2]
My implementation not work.
https://prnt.sc/pdgzsa https://prnt.sc/pdgzxy 
When I expanding parentLayout, there is no list. But if I put a button there, I see the button and first item of recyclerView

**Comment by skydoves** [comment]
@Pirokar 
Hi, thank you for your issue.
It seems the second layout could not measure the RecyclerView's height correctly.
Could you try again with the fixed height size of RecyclerView's item? like [this](https://github.com/skydoves/ExpandableLayout/blob/master/app/src/main/res/layout/item_section_child.xml).

**Comment by Pirokar** [comment]
@skydoves yes, it works with fixed height size. But I need NOT fixed height, depending of content size.

**Comment by skydoves** [comment]
@Pirokar 
Fixed and released a new version `1.0.1`.
Thank you :)
