### ISSUE TITLE
arrow view bug

### ISSUE THREAD

**Issue by dantariun** [skydoves/ExpandableLayout#22]
There is an unused arrow on the top right.
I tried to make the arrow invisible, but I can't access the view.

![2021-03-15 14;30;28](https://user-images.githubusercontent.com/26293122/111107982-4b055d80-859b-11eb-9180-66d9dbe3eb6b.PNG)

**Comment by skydoves** [comment]
If you don't want to show the spinner, try the below attribute.
```gradle
expandable_showSpinner="false"
```
Btw, the screenshot which you provided seems weird. (There are duplicated spinners) 
Does your parent & child view have arrows?.
