### ISSUE TITLE
toggleLayout() cannot be resolved

### ISSUE THREAD

**Issue by WenLonG12345** [skydoves/ExpandableLayout#24]
- Library Version - 1.0.6
 
Hi, recently I found this library and the implementation is great and simple. Thanks for it :)
But there is some problem regarding on the method `toggleLayout()`. I can't use this method as it stated as not resolved. 

Here is the screenshot. 
![Screenshot_1](https://user-images.githubusercontent.com/39330565/112116705-82a48300-8bf5-11eb-9f86-1ad4fcee5c2e.png)

I am using `Fragment` instead of `Activity`. Is it the problem exist because I am using Fragment? 

PS: I notice that there is no `toggleLayout()` in `ExpandableLayout.kt`

**Comment by skydoves** [comment]
Hi, sorry for the late reply.
The `toggleLayout()` function is included in the new version `1.0.7`.
Thanks :)
