### ISSUE TITLE
secondLayout not completely hide when collapsing 

### ISSUE THREAD

**Issue by WenLonG12345** [skydoves/ExpandableLayout#25]
- Library Version - 1.0.6
 
I had implement multiple `expandableLayout` and I notice that when collapsing the second `expandableLayout`, the `secondLayout` is not completely hide.

I am using `ScrollView` as my main's parent layout to make it scrollable. is it `ScrollView` makes the `secondLayout` work abnormally? 

https://user-images.githubusercontent.com/39330565/112133694-e84d3b00-8c06-11eb-9ef3-518627e6df9c.mp4

**Comment by skydoves** [comment]
Hi, a new version `1.0.7` has been released.
Please try using a new release. Thanks!

**Comment by WenLonG12345** [comment]
Thanks! Appreciate your contribution :)
