### ISSUE TITLE
Redundant amount of children's in View Hierarchy

### ISSUE THREAD

**Issue by MBratkowski** [skydoves/ExpandableLayout#3]
**Please complete the following information:**
- Library Version [v1.0.1]
- Affected Device(s) [Android Emulator]
 
**Describe the Bug:**
First thing - great job! I like this library, looks pretty nice and API is clear to use. Unfortunately, I found some issues with the View Hierarchy with the views which are associated.

Whenever method `updateExpandableLayout` invokes then we don't delete the previous elements of the view. In summary, we have an under the hood huge view hierarchy.

Current behaviour:

<img width="544" alt="Screenshot 2019-10-07 at 15 11 04" src="https://user-images.githubusercontent.com/6844181/66314716-b5c95880-e914-11e9-852a-3b61f3a5bc67.png">

I found some simple and fast fix to resolve this issue before invokes of `updateExpandableLayout` we add a `removeAllViews` method to clear our view, then view hierarchy looks much simpler.

<img width="494" alt="Screenshot 2019-10-07 at 15 09 18" src="https://user-images.githubusercontent.com/6844181/66314808-dee9e900-e914-11e9-8d5a-a5908e90fae3.png">

**Expected Behavior:**

We shouldn't have a redundant amount of views.

**Comment by skydoves** [comment]
@MBratkowski 
Hi, thank you for your issue :)
It is applied!
