### ISSUE TITLE
Second layout does not have the right height

### ISSUE THREAD

**Issue by fgnm** [skydoves/ExpandableLayout#5]
**Please complete the following information:**
- Library Version 1.0.3
- Affected Device(s) Generic device
 
I'm using this library inside a recyclerview. Each item in the recyclerview can be expanded, but the content of each item can vary, so the height is different for each item. The library seems to calculate the height for each item, however the height is not correct. For each item is always less the the real layout size.

**Expected Behavior:**

Since the content of each item is dynamic, the library should expose a method that can re mesure the height of the second layout.

**Comment by pierrekhouryy** [comment]
I seem to have this problem as well. Second layout if a horizontal scrollview and yet the more items are added to the scrollview the taller the second layout gets. any fix ?

**Comment by Imran-ss** [comment]
I am also facing similar issue.
Indeed I am able to reproduce in demo app as well, see the image.
![space_in_2nd_layout](https://user-images.githubusercontent.com/17312098/76955610-82194280-6938-11ea-8184-8c196e12cbd0.png)
I added some random number of second child then expand and collapse few time all items, then extra space has been added in 2nd layout.

**Comment by skydoves** [comment]
Hi, I fixed the measuring function internally, it's released a new version `1.0.5`.
If you check working well in a new version, this issue will be closed.
Thank you for your issue :)

**Comment by Imran-ss** [comment]
Thanks @skydoves the child space issue has fixed.
but after this fix I observe first time render of parent view is very slow.
seems like scroll issue as well.
expand any bottom parent  and then try to scroll up, you will notice scroll is not working properly.
