### ISSUE TITLE
The expandable layout height doesn't wrap the contained listView  

### ISSUE THREAD

**Issue by MohamedHatemAbdu** [skydoves/ExpandableLayout#7]
Why in your demo , when i decrease the number of items in the list, the expandable view doesn't wrap the list height as below ?

![image](https://user-images.githubusercontent.com/7180109/73934258-239b8600-48ef-11ea-83c5-7b2062da8434.png)

**Comment by MohamedHatemAbdu** [comment]
@skydoves 
I played a little in the `ExpandableLayout` class and after i commented the below lines, it works fine and wrapped the `listview `well. But in fact i don't know what these lines do :'( 

![image](https://user-images.githubusercontent.com/7180109/74089045-02cd5f00-4aae-11ea-897f-28289845f371.png)

![image](https://user-images.githubusercontent.com/7180109/74089063-298b9580-4aae-11ea-834b-b01fe6aade3e.png)

What do you think ?

**Comment by MohamedHatemAbdu** [comment]
@skydoves  
I played a little with `ExpandableLayout `class and after i added the below line it works with me fine. but in fact i don't why ?
![image](https://user-images.githubusercontent.com/7180109/74092899-b6007d00-4adb-11ea-9bc8-ef702424cb57.png)
![image](https://user-images.githubusercontent.com/7180109/74092900-bef14e80-4adb-11ea-9496-4d16686b33ad.png)

Could you advise ?

**Comment by skydoves** [comment]
@MohamedHatemAbdu 
Hi, I think if the `secondlayout` is a `RecyclerView`, the flow will go to the `ViewGroup` case. 
Because `RecyclerView` is a `ViewGroup`.

`RecyclerView` is a `ViewGroup` but It doesn't have any `View` child via added `addView`.
So I think using `child.measuredHeight` is more correct instead of using `setMeasureHeight`.
Thank you for your issue :)

This will be applied to the next release!

**Comment by MohamedHatemAbdu** [comment]
@skydoves There is another issue :

The `recyclerview `doesn't retain it's status correctly. 
If you have many items in the list and you expanded only the first item in the list, may be you find other items in the list expanded (but you didn't expand them) due to the recycling. 

And i think this issue due to we save the status of expanding in `Expandablelayout `view itself through a Boolean var `isExpandable`.

**Comment by Imran-ss** [comment]
> This will be applied to the next release!

Hi @skydoves when are you planning to release this?
I am also getting same issue.

**Comment by skydoves** [comment]
Hi, I fixed the measuring function internally, it's released a new version `1.0.5`.
If you check working well in a new version, this issue will be closed.
Thank you for your issue :)

**Comment by skydoves** [comment]
Duplicated #5.
